### ISSUE TITLE
Error starting megaclisas-statusd on megaraid_sas module

### ISSUE THREAD

**Issue by andyshinn** [debops/ansible-hwraid#6]
I'm getting an error on my Dell PERC (MegaRAID SAS) machines that it cannot start `megaclisas-statusd`:

```
TASK [debops.hwraid : Make sure service starts at boot] ************************
skipping: [cloud-transfer12.natera.local] => (item=({u'packages': [u'tw_cli', u'3ware-status'], u'module': u'3w_xxxx'}, u'3ware-statusd')) 
skipping: [cloud-transfer12.natera.local] => (item=({u'packages': [u'tw_cli', u'3ware-status'], u'module': u'3w_9xxx'}, u'3ware-statusd')) 
skipping: [cloud-transfer12.natera.local] => (item=({u'packages': [u'mpt-status'], u'module': u'mptsas'}, u'mpt-statusd')) 
skipping: [cloud-transfer12.natera.local] => (item=({u'packages': [u'sas2ircu', u'sas2ircu-status'], u'module': u'mpt2sas'}, u'sas2ircu-statusd')) 
skipping: [cloud-transfer12.natera.local] => (item=({u'packages': [u'megactl', u'megaraid-status'], u'module': u'megaraid_mm'}, u'megaraid-statusd')) 
skipping: [cloud-transfer12.natera.local] => (item=({u'packages': [u'megactl', u'megaraid-status'], u'module': u'megaraid_mbox'}, u'megaraid-statusd')) 
failed: [cloud-transfer12.natera.local] (item=({u'packages': [u'megactl', u'megaraid-status'], u'module': u'megaraid_sas'}, u'megaclisas-statusd')) => {"failed": true, "item": [{"module": "megaraid_sas", "packages": ["megactl", "megaraid-status"]}, "megaclisas-statusd"], "msg": "no service or tool found for: megaclisas-statusd"}
skipping: [cloud-transfer12.natera.local] => (item=({u'packages': [u'arcconf', u'aacraid-status'], u'module': u'aacraid'}, u'aacraid-statusd')) 
skipping: [cloud-transfer12.natera.local] => (item=({u'packages': [u'cciss-vol-status'], u'module': u'cciss'}, u'cciss-vol-statusd')) 
```

It appears to install `megaraid-status` and `megactl` from the `megaraid_sas` module at https://github.com/debops/ansible-hwraid/blob/master/defaults/main.yml#L58-L60. But `megaclisas-statusd` is actually provided by `megaclisas-status` package.

So it would appear that either the `megaraid_sas` module should change the service name to `megaraidsas-statusd` (which is installed via the `megaraid-status` package) or also install the `megaclisas-status` package which will provide the `megaclisas-statusd` service.

I just modified the daemon to be `megaraidsas-statusd` instead of `megaclisas-statusd` in my environment and it works fine. It seems like `megaraid-status` and `megaclisas-status` perform pretty much the same function.

I'm happy to open a PR for this if it is indeed a bug. But I'm not sure which direction more proper. Any ideas?

**Comment by drybjed** [comment]
Sounds like changing the service to manage `megaraidsas-statusd` is the better way to go. Thanks for the bug report. :-)
